// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/multiply": {
            "post": {
                "description": "Умножает все числа из массива запроса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "multiply"
                ],
                "summary": "Произведение чисел",
                "parameters": [
                    {
                        "description": "Массив чисел и токен пользователя",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NumbersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный результат с произведением",
                        "schema": {
                            "$ref": "#/definitions/models.MultiplyResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка: \"Invalid request body\" или \"Empty request body\" ",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sum": {
            "post": {
                "description": "Складывает все числа из запроса и сохраняется результат по токену",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sum"
                ],
                "summary": "Сложение чисел",
                "parameters": [
                    {
                        "description": "Массив чисел и токен пользователя",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NumbersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный результат с суммой",
                        "schema": {
                            "$ref": "#/definitions/models.SumResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка: \"Invalid request body\" или \"Empty request body\" ",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "description": "ErrorResponse представляет исходящий JSON со строкой ошибки (\"Invalid request body\" или \"Empty request body\")",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        },
        "models.MultiplyResponse": {
            "description": "MultiplyResponse представляет исходящий JSON с целым числом",
            "type": "object",
            "properties": {
                "multiply": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "models.NumbersRequest": {
            "description": "NumbersRequest представляет входной JSON с массивом чисел и токеном",
            "type": "object",
            "properties": {
                "numbers": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        4
                    ]
                },
                "token": {
                    "type": "string",
                    "example": "82a51b41-b7c7-4405-859e-7936xxxxxxxx"
                }
            }
        },
        "models.SumResponse": {
            "description": "SumResponse представляет исходящий JSON с целым числом",
            "type": "object",
            "properties": {
                "sum": {
                    "type": "integer",
                    "example": 7
                }
            }
        }
    },
    "tags": [
        {
            "description": "Вычисление суммы",
            "name": "sum"
        },
        {
            "description": "Вычисление произведения",
            "name": "multiply"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CalculatorAPI",
	Description:      "Это API для вычисления суммы и произведения",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
